import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hell&Co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <div className={styles.container}>
          <div className={`${styles.tentang}`}>
            <h1>Tentang Kami</h1>
            <p>Berikan Hadiah Yang Terbaik Untuk Orang Tersayang</p>
            <p className=' text-light m-1'>Perusahaan cincin custom anak bangsa yang berdiri sejak 2015 ini dikenal dengan kualitas dan pelayanannya. Terbukti dengan adanya lebih dari 3000 ulasan di Google Bisnis dengan rating 4.9 dari pelanggannya.

              Tidak hanya fokus dengan produksi cincin emas saja, Kotagede Jewellery juga menyediakan cincin secara custom dari bahan non emas seperti PLATIDIUM dan Palladium yang halal dan bersifat anti alergi.

              Kami hadir untuk memberikan solusi bagi pasangan yang kesulitan mendapatkan cincin dengan model trendy dan sesuai dengan ukuran dan gaya pemakainya.

              Demi menjaga kualitasnya, kami hanya menggunakan bahan dari Emas Antam asli dan logam bersertifikat BATAN dengan dibantu pengrajin handal profesional, bahkan menjamin produk dengan garansi hingga 10 tahun.
            </p>
            <button className="btn m-2">Hubungi kami</button>
          </div>
        </div>
        <div className={`${styles.container}`}>
          <h1>Kenapa Memilih Kami</h1>
          <div className={`${styles.itemList}`}>
            <div className={`${styles.item}`}>
              <Image
                alt='thumb'
                src="/thumbs.svg"
                width={80}
                height={80}
              />
              <p className='text-center mx-auto mt-2'>Terpercaya</p>
            </div>
            <div className={`${styles.item}`}>
              <Image
                alt='dompet'
                src="/dompet.svg"
                width={80}
                height={80}
              />
              <p className='text-center mx-auto mt-2'>Terpercaya</p>
            </div>
            <div className={`${styles.item}`}>
              <Image
                alt='kado'
                src="/love.svg"
                width={80}
                height={80}
              />
              <p className='text-center mx-auto mt-2'>Terpercaya</p>
            </div>
            <div className={`${styles.item}`}>
              <Image
                alt='love'
                src="/kado.svg"
                width={80}
                height={80}
              />
              <p className='text-center mx-auto mt-2'>Terpercaya</p>
            </div>
          </div>
        </div>

        <div className={`${styles.container}`}>
          <div className={`${styles.cardList}`}>
            <div className={`${styles.textLeft}`}>
              <p className=' text-uppercase'>BELI SEKARANG</p>
              <h2>Best products</h2>
              <p>Kami membuat cincin dengan berlian yang sangat langka, Dengan melakukan itu, kami menciptakan sesuatu yang tidak hanya brilian, tetapi juga legendaris.</p>
              <button className='btn '>Lihat Semua Product</button>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
              <div className={`${styles.crText}`}>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt itaque praesentium officiis dolorum quaerat veniam ipsa et deserunt repellendus possimus.</p>
                <h3>Rp. 10.000.000</h3>
              </div>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
              <div className={`${styles.crText}`}>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt itaque praesentium officiis dolorum quaerat veniam ipsa et deserunt repellendus possimus.</p>
                <h3>Rp. 10.000.000</h3>
              </div>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
              <div className={`${styles.crText}`}>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt itaque praesentium officiis dolorum quaerat veniam ipsa et deserunt repellendus possimus.</p>
                <h3>Rp. 10.000.000</h3>
              </div>
            </div>

          </div>
        </div>

        <div className={`${styles.main}`}>
          <h1>KOLEKSI KAMI</h1>
          <div className={`${styles.collection}`}>
            <div className={`${styles.catalog}`}>
              <Image
                src="/product/collection1.png"
                alt="collection-item1"
                height={150}
                width={150}
                object-fit="fill"
                className={`${styles.imgCatalog}`} />
              <div className="text ">
                <p>this cinsin a</p>
              </div>
            </div>
            <div className={`${styles.catalog}`}>
              <Image
                src="/product/collection1.png"
                alt="collection-item1"
                height={150}
                width={150}
                object-fit="fill"
                className={`${styles.imgCatalog}`} />
              <div className="text ">
                <p>this cinsin a</p>
              </div>
            </div>
            <div className={`${styles.catalog}`}>
              <Image
                src="/product/collection1.png"
                alt="collection-item1"
                height={150}
                width={150}
                object-fit="fill"
                className={`${styles.imgCatalog}`} />
              <div className="text ">
                <p>this cinsin a</p>
              </div>
            </div>
            <div className={`${styles.catalog}`}>
              <Image
                src="/product/collection1.png"
                alt="collection-item1"
                height={150}
                width={150}
                object-fit="fill"
                className={`${styles.imgCatalog}`} />
              <div className="text ">
                <p>this cinsin a</p>
              </div>
            </div>
            <div className={`${styles.catalog}`}>
              <Image
                src="/product/collection1.png"
                alt="collection-item1"
                height={150}
                width={150}
                object-fit="fill"
                className={`${styles.imgCatalog}`} />
              <div className="text ">
                <p>this cinsin a</p>
              </div>
            </div>
          </div>
        </div>

        <div className={`${styles.container}`}>
          <div className={`${styles.cardList}`}>
            <div className={`${styles.textLeft}`}>
              <p className=' text-uppercase'>Testimonial</p>
              <h2>Testimoni pembeli</h2>
              <p>Beberapa testimonial dari pembeli setia kami yang sudah melakukan pemesanan cincin di kotagedejewellery</p>
              <button className='btn '>Lihat Semua Testimonial</button>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
            </div>
            <div className={`${styles.cardRight} shadow-sm`}>
              <div className={`${styles.imgCr}`}>
                <Image
                  alt='Cr-1'
                  src="/product/cr1.png"
                  width={200}
                  height={200}
                  object-fit="fill"
                />
              </div>
            </div>

          </div>
        </div>

        <div className={`${styles.container}`}>
          <div className={`${styles.layanan}`}>
            <h1>Apakah anda puas dengan pelayanan kami?</h1>
            <button >Kirim Feedback</button>
          </div>
        </div>

        <div className={`${styles.footer}`}>

        </div>
      </body>
    </>
  )
}
