import Head from "next/head"

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Hell&Co</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </>
    )
}

export default Layout